-- SENTINEL v2 — initial schema
-- Core tables: aircraft, flight events, behavioral baselines, anomaly flags, users.

CREATE TABLE aircraft (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao_hex    VARCHAR(16) NOT NULL,
    callsign    VARCHAR(16),
    category    VARCHAR(64),
    first_seen  TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_aircraft_icao UNIQUE (icao_hex)
);
CREATE INDEX idx_aircraft_last_seen ON aircraft (last_seen);

CREATE TABLE flight_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id BIGINT NOT NULL REFERENCES aircraft (id) ON DELETE CASCADE,
    altitude_ft DOUBLE PRECISION,
    speed_kts   DOUBLE PRECISION,
    heading_deg DOUBLE PRECISION,
    lat         DOUBLE PRECISION,
    lon         DOUBLE PRECISION,
    recorded_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_event_aircraft_time ON flight_event (aircraft_id, recorded_at DESC);
CREATE INDEX idx_event_recorded_at ON flight_event (recorded_at DESC);

CREATE TABLE baseline (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id     BIGINT NOT NULL REFERENCES aircraft (id) ON DELETE CASCADE,
    avg_altitude_ft DOUBLE PRECISION,
    avg_speed_kts   DOUBLE PRECISION,
    avg_heading_deg DOUBLE PRECISION,
    avg_lat         DOUBLE PRECISION,
    avg_lon         DOUBLE PRECISION,
    -- Rolling-window stats (Welford incremental): v2 replaces v1 all-time means
    std_altitude_ft DOUBLE PRECISION,
    std_speed_kts   DOUBLE PRECISION,
    event_count     INTEGER NOT NULL DEFAULT 0,
    window_start    TIMESTAMPTZ,
    calculated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_baseline_aircraft UNIQUE (aircraft_id)
);

CREATE TABLE anomaly (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id     BIGINT NOT NULL REFERENCES aircraft (id) ON DELETE CASCADE,
    event_id        BIGINT NOT NULL REFERENCES flight_event (id) ON DELETE CASCADE,
    score           DOUBLE PRECISION NOT NULL,
    -- Per-dimension z-scores for explainability
    z_altitude      DOUBLE PRECISION,
    z_speed         DOUBLE PRECISION,
    z_heading       DOUBLE PRECISION,
    z_position      DOUBLE PRECISION,
    explanation     TEXT,
    explanation_src VARCHAR(16) NOT NULL DEFAULT 'rule',
    flagged_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    acknowledged    BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_anomaly_aircraft_time ON anomaly (aircraft_id, flagged_at DESC);
CREATE INDEX idx_anomaly_flagged_at ON anomaly (flagged_at DESC);
CREATE INDEX idx_anomaly_unacked ON anomaly (acknowledged, flagged_at DESC) WHERE acknowledged = FALSE;

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(16) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_username UNIQUE (username),
    CONSTRAINT chk_user_role CHECK (role IN ('ANALYST', 'OPERATOR', 'ADMIN'))
);
